version: '3.8'

services:
  zephyr:
    build:
      context: .
      dockerfile: Dockerfile.espressif
    image: esp32-zephyr
    container_name: esp32-zephyr
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace:cached
    ports:
      - "3333:3333"
      - "2222:2222"
